version: 2
jobs:
  build:
    docker:
      - image: edvisor/node:8-build
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
    - checkout
    - restore_cache:
        keys:
          - gem-cache-{{ checksum "Gemfile.lock" }}
    - run:
        name: Setup
        command: |
          bundle check || bundle install --without development test
          npm install -g @2fd/graphdoc
    - save_cache:
        key: gem-cache-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run:
        name: Deploy Staging
        command: |
          cp .gitconfig $HOME/.gitconfig
          ./deploy.sh

workflows:
  version: 2
  deploy-docs:
    jobs:
      - build:
          filters:
            branches:
              only: master

