version: 2
jobs:
  deploy-docs:
    docker:
      - image: edvisor/node:8-build
    steps:
    - checkout
    - restore_cache:
        keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
    - run:
        name: Setup
        command: |
          bundle install
          npm install -g @2fd/graphdoc
    - save_cache:
        key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run:
        name: Deploy Staging
        command: ./deploy.sh && ./restore-cname.sh

workflows:
  version: 2
  deploy-docs:
    jobs:
      - deploy-docs:
          filters:
            branches:
              only: master
